# Generated by Django 5.0.7 on 2024-08-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samvidhan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundamentalRights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_number", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("simplified_text", models.TextField()),
            ],
        ),
    ]
