# Generated by Django 5.0.7 on 2024-08-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samvidhan", "0005_fundamentalrights_summary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Average", "Average"),
                            ("Poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("what_you_learned", models.TextField()),
                ("was_it_easy", models.BooleanField(default=True)),
                ("suggestions", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
