# Generated by Django 5.0.7 on 2024-08-28 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("samvidhan", "0006_userfeedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfeedback",
            name="was_it_easy",
        ),
        migrations.RemoveField(
            model_name="userfeedback",
            name="what_you_learned",
        ),
    ]
